name: build

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build_host:
    name: Build Host
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: |
          bash scripts/build.sh \
            -n \
            -O2 \
            -T \
            x86_64-linux-musl
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: x86_64-linux-musl-native
          path: dist/x86_64-linux-musl-native

  build_job_1:
    name: Build
    runs-on: ubuntu-latest
    needs: build_host
    steps:
      - name: Download native
        uses: actions/download-artifact@v4
        with:
          name: x86_64-linux-musl-native
          path: /tmp/x86_64-linux-musl-native
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: |
          chmod -R 0755 /tmp/x86_64-linux-musl-native
          TARGETS="$(sed -n '11,20p' scripts/triples.txt)"
          echo "$TARGETS"
          bash scripts/build.sh \
            -nt \
            -c "/tmp/x86_64-linux-musl-native/bin/x86_64-linux-musl-gcc" \
            -x "/tmp/x86_64-linux-musl-native/bin/x86_64-linux-musl-g++" \
            -T \
            "$TARGETS"

  build_job_2:
    name: Build
    runs-on: ubuntu-latest
    needs: build_host
    steps:
      - name: Download native
        uses: actions/download-artifact@v4
        with:
          name: x86_64-linux-musl-native
          path: /tmp/x86_64-linux-musl-native
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: |
          chmod -R 0755 /tmp/x86_64-linux-musl-native
          TARGETS="$(sed -n '11,20p' scripts/triples.txt)"
          echo "$TARGETS"
          bash scripts/build.sh \
            -nt \
            -c "/tmp/x86_64-linux-musl-native/bin/x86_64-linux-musl-gcc" \
            -x "/tmp/x86_64-linux-musl-native/bin/x86_64-linux-musl-g++" \
            -T \
            "$TARGETS"

  build_job_3:
    name: Build
    runs-on: ubuntu-latest
    needs: build_host
    steps:
      - name: Download native
        uses: actions/download-artifact@v4
        with:
          name: x86_64-linux-musl-native
          path: /tmp/x86_64-linux-musl-native
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: |
          chmod -R 0755 /tmp/x86_64-linux-musl-native
          TARGETS="$(sed -n '21,30p' scripts/triples.txt)"
          echo "$TARGETS"
          bash scripts/build.sh \
            -nt \
            -c "/tmp/x86_64-linux-musl-native/bin/x86_64-linux-musl-gcc" \
            -x "/tmp/x86_64-linux-musl-native/bin/x86_64-linux-musl-g++" \
            -T \
            "$TARGETS"

  build_job_4:
    name: Build
    runs-on: ubuntu-latest
    needs: build_host
    steps:
      - name: Download native
        uses: actions/download-artifact@v4
        with:
          name: x86_64-linux-musl-native
          path: /tmp/x86_64-linux-musl-native
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: |
          chmod -R 0755 /tmp/x86_64-linux-musl-native
          TARGETS="$(sed -n '31,40p' scripts/triples.txt)"
          echo "$TARGETS"
          bash scripts/build.sh \
            -nt \
            -c "/tmp/x86_64-linux-musl-native/bin/x86_64-linux-musl-gcc" \
            -x "/tmp/x86_64-linux-musl-native/bin/x86_64-linux-musl-g++" \
            -T \
            "$TARGETS"

  build_job_5:
    name: Build
    runs-on: ubuntu-latest
    needs: build_host
    steps:
      - name: Download native
        uses: actions/download-artifact@v4
        with:
          name: x86_64-linux-musl-native
          path: /tmp/x86_64-linux-musl-native
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: |
          chmod -R 0755 /tmp/x86_64-linux-musl-native
          TARGETS="$(sed -n '41,50p' scripts/triples.txt)"
          echo "$TARGETS"
          bash scripts/build.sh \
            -nt \
            -c "/tmp/x86_64-linux-musl-native/bin/x86_64-linux-musl-gcc" \
            -x "/tmp/x86_64-linux-musl-native/bin/x86_64-linux-musl-g++" \
            -T \
            "$TARGETS"

  build_job_6:
    name: Build
    runs-on: ubuntu-latest
    needs: build_host
    steps:
      - name: Download native
        uses: actions/download-artifact@v4
        with:
          name: x86_64-linux-musl-native
          path: /tmp/x86_64-linux-musl-native
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: |
          chmod -R 0755 /tmp/x86_64-linux-musl-native
          TARGETS="$(sed -n '51,60p' scripts/triples.txt)"
          echo "$TARGETS"
          bash scripts/build.sh \
            -nt \
            -c "/tmp/x86_64-linux-musl-native/bin/x86_64-linux-musl-gcc" \
            -x "/tmp/x86_64-linux-musl-native/bin/x86_64-linux-musl-g++" \
            -T \
            "$TARGETS"
