name: build-on-linux-riscv64

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  init:
    name: Init
    runs-on: ubuntu-latest
    outputs:
      TARGETS: ${{ steps.get_all_targets.outputs.TARGETS }}
    steps:
      - uses: actions/checkout@v4

      - name: Get all targets
        id: get_all_targets
        run: |
          declare -a arr=()
          while IFS= read -r line; do
          if [ -z "$line" ] || [ "${line:0:1}" == "#" ]; then
            continue
          fi
          arr+=("$line")
          done < scripts/triples.txt
          printf -v json '"%s",' "${arr[@]}"
          json="[${json%,}]"
          echo "TARGETS=$json" >> $GITHUB_OUTPUT

      - name: Init sources
        run: |
          make extract_all

      - uses: actions/upload-artifact@v4
        with:
          name: sources
          path: sources

  build_targets_on_linux_riscv64_cross:
    name: Build cross
    runs-on: ubuntu-latest
    needs:
      - init
    strategy:
      matrix:
        targets: ${{ fromJSON(needs.init.outputs.TARGETS) }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          name: sources
          path: sources

      - uses: uraimo/run-on-arch-action@v2
        name: Build
        id: build
        with:
          arch: riscv64
          distro: ubuntu_latest
          githubToken: ${{ github.token }}
          dockerRunArgs: |
            --volume "${PWD}:/build"
          shell: /bin/bash
          install: |
            apt update && apt install -y \
              coreutils \
              curl \
              bzip2 \
              xz-utils \
              make \
              bison \
              rsync \
              patch \
              g++
          run: |
            cd /build
            bash scripts/build.sh \
                -LO1 \
                -T "${{ matrix.targets }}"

      - name: Upload ${{ matrix.targets }} cross
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.targets }}-cross-linux-riscv64
          path: dist/${{ matrix.targets }}-cross

  build_targets_on_linux_riscv64_native:
    name: Build native
    runs-on: ubuntu-latest
    needs:
      - init
      - build_targets_on_linux_riscv64_cross
    strategy:
      matrix:
        targets: ${{ fromJSON(needs.init.outputs.TARGETS) }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          name: sources
          path: sources

      - uses: actions/download-artifact@v4
        with:
          name: ${{ matrix.targets }}-cross-linux-riscv64
          path: dist/${{ matrix.targets }}-cross

      - uses: uraimo/run-on-arch-action@v2
        name: Build
        id: build
        with:
          arch: riscv64
          distro: ubuntu_latest
          githubToken: ${{ github.token }}
          dockerRunArgs: |
            --volume "${PWD}:/build"
          shell: /bin/bash
          install: |
            apt update && apt install -y \
              coreutils \
              curl \
              bzip2 \
              xz-utils \
              make \
              bison \
              rsync \
              patch \
              g++
          run: |
            cd /build
            bash scripts/build.sh \
                -NLO1 \
                -T "${{ matrix.targets }}"

      - name: Upload ${{ matrix.targets }} native
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.targets }}-native-linux-riscv64
          path: dist/${{ matrix.targets }}-native
