name: build

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build_host:
    name: Build Host
    runs-on: ubuntu-latest
    outputs:
      TARGETS: ${{ steps.get_all_targets.outputs.TARGETS }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get all targets
        id: get_all_targets
        run: |
          declare -a arr=()
          while IFS= read -r line; do
          if [ -z "$line" ]; then
            continue
          fi
          arr+=("$line")
          done < scripts/triples.txt
          printf -v json '"%s",' "${arr[@]}"
          json="[${json%,}]"
          echo "TARGETS=$json" >> $GITHUB_OUTPUT

      - name: Cache sources
        id: cache-sources
        uses: actions/cache@v4
        with:
            path: sources
            key: sources

      - name: Build
        run: |
          bash scripts/build.sh \
            -n \
            -O2 \
            -T \
            x86_64-linux-musl

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: x86_64-linux-musl-native
          path: dist/x86_64-linux-musl-native

  build_targets:
    name: Build Targets
    runs-on: ubuntu-latest
    needs: build_host
    strategy:
      max-parallel: 8
      matrix:
        targets: ${{ fromJSON(needs.build_host.outputs.TARGETS) }}
    steps:
      - name: Download native
        uses: actions/download-artifact@v4
        with:
          name: x86_64-linux-musl-native
          path: /tmp/x86_64-linux-musl-native

      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache sources
        id: cache-sources
        uses: actions/cache@v4
        with:
            path: sources
            key: sources

      - name: Build
        run: |
          chmod -R 0755 /tmp/x86_64-linux-musl-native
          bash scripts/build.sh \
            -ntO0 \
            -c "/tmp/x86_64-linux-musl-native/bin/x86_64-linux-musl-gcc" \
            -x "/tmp/x86_64-linux-musl-native/bin/x86_64-linux-musl-g++" \
            -T "${{ matrix.targets }}"
