name: build-on-linux-amd64

on:
  workflow_dispatch:

jobs:
  init:
    name: Init
    runs-on: ubuntu-latest
    outputs:
      TARGETS: ${{ steps.get_all_targets.outputs.TARGETS }}
    steps:
      - uses: actions/checkout@v4

      - name: Get all targets
        id: get_all_targets
        run: |
          declare -a arr=()
          while IFS= read -r line; do
          if [ -z "$line" ] || [ "${line:0:1}" == "#" ]; then
            continue
          fi
          arr+=("$line")
          done < scripts/triples.txt
          printf -v json '"%s",' "${arr[@]}"
          json="[${json%,}]"
          echo "TARGETS=$json" >> $GITHUB_OUTPUT

  build_targets_on_linux_amd64:
    name: Build
    runs-on: ubuntu-latest
    needs:
      - init
    strategy:
      matrix:
        targets: ${{ fromJSON(needs.init.outputs.TARGETS) }}
    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: |
          unamespacer=$(uname -s | tr '[:upper:]' '[:lower:]')-$(uname -m)
          NATIVE_COMPILER="https://github.com/${{ github.repository }}/releases/download/0.4.4/x86_64-linux-musl-native-${unamespacer}.tgz"
          NATIVE_COMPILER_STATUS=$(curl -sILo /dev/null -w "%{http_code}\n" $NATIVE_COMPILER)
          if [ $NATIVE_COMPILER_STATUS -ne 200 ]; then apk add --no-cache g++; else mkdir -p "x86_64-linux-musl-native" && curl -sL "$NATIVE_COMPILER" | tar -zxf - -C "x86_64-linux-musl-native" --strip-components 1 && chmod -R 0755 x86_64-linux-musl-native && export PATH="$PWD/x86_64-linux-musl-native/bin:$PATH"; fi
          bash scripts/build.sh \
            -nLO1 \
            -T "${{ matrix.targets }}"

      - name: Upload ${{ matrix.targets }} cross
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.targets }}-cross
          path: dist/${{ matrix.targets }}-cross

      - name: Upload ${{ matrix.targets }} native
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.targets }}-native
          path: dist/${{ matrix.targets }}-native
