name: release_dev

on:
  workflow_dispatch:

jobs:
  init:
    name: Init
    runs-on: ubuntu-latest
    outputs:
      TARGETS: ${{ steps.get_all_targets.outputs.TARGETS }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get all targets
        id: get_all_targets
        run: |
          declare -a arr=()
          while IFS= read -r line; do
          if [ -z "$line" ] || [ "${line:0:1}" == "#" ]; then
            continue
          fi
          arr+=("$line")
          done < scripts/triples.txt
          printf -v json '"%s",' "${arr[@]}"
          json="[${json%,}]"
          echo "TARGETS=$json" >> $GITHUB_OUTPUT

      - name: Init sources
        run: |
          make extract_all

      - name: Upload sources
        uses: actions/upload-artifact@v4
        with:
          name: sources
          path: sources

  build_linux_amd64_host:
    name: Build Linux amd64 Host
    runs-on: ubuntu-latest
    needs:
      - init
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download sources
        uses: actions/download-artifact@v4
        with:
          name: sources
          path: sources

      - name: Build
        run: |
          bash scripts/build.sh \
            -nL \
            -O2 \
            -T \
            x86_64-linux-musl

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: tmp x86_64-linux-musl-native
          path: dist/x86_64-linux-musl-native

  build_targets_on_linux_amd64:
    name: Build Targets on Linux amd64
    runs-on: ubuntu-latest
    needs:
      - init
      - build_linux_amd64_host
    strategy:
      matrix:
        targets: ${{ fromJSON(needs.init.outputs.TARGETS) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download native
        uses: actions/download-artifact@v4
        with:
          name: tmp x86_64-linux-musl-native
          path: /tmp/x86_64-linux-musl-native

      - name: Download sources
        uses: actions/download-artifact@v4
        with:
          name: sources
          path: sources

      - name: Build
        run: |
          chmod -R 0755 /tmp/x86_64-linux-musl-native
          export PATH=/tmp/x86_64-linux-musl-native/bin:$PATH
          bash scripts/build.sh \
            -anL \
            -c "x86_64-linux-musl-gcc" \
            -x "x86_64-linux-musl-g++" \
            -T "${{ matrix.targets }}"

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: dev-linux-amd64
          draft: false
          prerelease: true
          append_body: false
          fail_on_unmatched_files: true
          files: |
            dist/*.tgz

  build_targets_on_macos_amd64:
    name: Build Targets on macOS amd64
    runs-on: macos-latest
    needs:
      - init
    strategy:
      matrix:
        targets: ${{ fromJSON(needs.init.outputs.TARGETS) }}
        exclude:
          - targets:
            - i486-w64-mingw32
            - i686-w64-mingw32
            - x86_64-w64-mingw32
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download sources
        uses: actions/download-artifact@v4
        with:
          name: sources
          path: sources

      - name: Init Dependencies
        run: |
          brew install llvm
          brew install make
          brew install gnu-sed
          brew install gawk
          brew install coreutils
          brew install findutils

      - name: Build
        run: |
          bash scripts/build.sh \
            -asL \
            -c "llvm-gcc" \
            -x "llvm-g++" \
            -T "${{ matrix.targets }}"

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: dev-macos-amd64
          draft: false
          prerelease: true
          append_body: false
          fail_on_unmatched_files: true
          files: |
            dist/*.tgz
