name: releases-on-darwin-amd64

on:
  push:
    tags:
      - "v*"

jobs:
  init:
    name: Init
    runs-on: ubuntu-latest
    outputs:
      TARGETS: ${{ steps.get_all_targets.outputs.TARGETS }}
      VERSION: ${{ steps.get_version.outputs.VERSION }}
    steps:
      - uses: actions/checkout@v4

      - name: Get all targets
        id: get_all_targets
        run: |
          declare -a arr=()
          while IFS= read -r line; do
          if [ -z "$line" ] || [ "${line:0:1}" == "#" ]; then
            continue
          fi
          arr+=("$line")
          done < scripts/triples.txt
          printf -v json '"%s",' "${arr[@]}"
          json="[${json%,}]"
          echo "TARGETS=$json" >> $GITHUB_OUTPUT

      - name: Get version
        id: get_version
        run: echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_OUTPUT

      - name: Init sources
        run: |
          make extract_all

      - uses: actions/upload-artifact@v4
        with:
          name: sources
          path: sources

  releases_targets_on_macos_amd64:
    name: Build
    runs-on: macos-13
    needs:
      - init
    strategy:
      matrix:
        targets: ${{ fromJSON(needs.init.outputs.TARGETS) }}
        exclude:
          - targets: powerpc64le-linux-musl
    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          name: sources
          path: sources

      - name: Init Dependencies
        run: |
          brew install \
            make \
            gnu-sed \
            gawk \
            coreutils \
            findutils

      - name: Build
        id: build
        run: |
          echo ::set-output name=unamespacer::$(uname -s | tr '[:upper:]' '[:lower:]')-$(uname -m)
          bash scripts/build.sh \
            -sL \
            -T "${{ matrix.targets }}"

      - name: Archive
        run: |
          mkdir -p archive
          tar -zcvf archive/${{ matrix.targets }}-cross-${{ steps.build.outputs.unamespacer }}.tgz \
            -C dist/${{ matrix.targets }}-cross \
            .

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ needs.init.outputs.VERSION }}
          draft: false
          prerelease: false
          append_body: false
          fail_on_unmatched_files: true
          files: |
            archive/*.tgz