name: release_dev

on:
  workflow_dispatch:

jobs:
  build_host:
    name: Build Host
    runs-on: ubuntu-latest
    outputs:
      TARGETS: ${{ steps.get_all_targets.outputs.TARGETS }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get all targets
        id: get_all_targets
        run: |
          declare -a arr=()
          while IFS= read -r line; do arr+=("$line"); done < scripts/triples.txt
          printf -v json '"%s",' "${arr[@]}"
          json="[${json%,}]"
          echo "TARGETS=$json" >> $GITHUB_OUTPUT

      - name: Build
        run: |
          bash scripts/build.sh \
            -n \
            -O2 \
            -T \
            x86_64-linux-musl

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: x86_64-linux-musl-native
          path: dist/x86_64-linux-musl-native

  build_targets:
    name: Build Targets
    runs-on: ubuntu-latest
    needs: build_host
    strategy:
      matrix:
        targets: ${{ fromJSON(needs.build_host.outputs.TARGETS) }}
    steps:
      - name: Download native
        uses: actions/download-artifact@v4
        with:
          name: x86_64-linux-musl-native
          path: /tmp/x86_64-linux-musl-native

      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: |
          if [ -z "${{ matrix.targets }}" ]; then
            exit 0
          fi
          chmod -R 0755 /tmp/x86_64-linux-musl-native
          bash scripts/build.sh \
            -an \
            -c "/tmp/x86_64-linux-musl-native/bin/x86_64-linux-musl-gcc" \
            -x "/tmp/x86_64-linux-musl-native/bin/x86_64-linux-musl-g++" \
            -T "${{ matrix.targets }}"

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          draft: false
          prerelease: true
          append_body: false
          fail_on_unmatched_files: true
          files: |
            dist/*
